### ISSUE TITLE
As a user, I want to see the dash board.

### ISSUE THREAD

**Issue by Deshadii** [ousl-group-alpha-l4/test-project1#1]

**Comment by mohamedsakeel** [comment]
I cant do this. Do yourself 😆

**Comment by Deshadii** [comment]
@nirmalOUSL You have to do this quckly

**Comment by Deshadii** [comment]
@mohamedsakeel you are a irresponsible worker

**Comment by mohamedsakeel** [comment]
@Deshadii @nirmalOUSL I am going by bye

**Comment by mohamedsakeel** [comment]
> @mohamedsakeel you are a irresponsible worker

you are

**Comment by nirmalOUSL** [comment]
ok madam @Deshadii

**Comment by mohamedsakeel** [comment]
> ok madam @Deshadii

Good boy

**Comment by mohamedsakeel** [comment]
this is the biggest issue

**Comment by Deshadii** [comment]
bye everyone.  I'm kick out both of you from my company

**Comment by nirmalOUSL** [comment]
you cant fire me. I quit

**Comment by mohamedsakeel** [comment]
### **Bye**
